source 'https://github.com/CocoaPods/Specs.git'

project 'KINWebBrowserExample.xcodeproj'
platform :ios, :deployment_target => '8.0'


target "KINWebBrowserExample" do
	pod "KINWebBrowser", :path => "../KINWebBrowser.podspec"
end
